#Chosen Parameters
MIN_VEHICLE_SPEED = 50 / 3.6  # m/s
MAX_VEHICLE_SPEED = 90 / 3.6 # m/s
VEHICLE_ARRIVAL_RATE = 0.2  # poisson parameter, 1/seconds
LANE_WIDTH = 4 # meters
LANE_LENGTH = 2000 # meters
NUM_LANES = 6 # number of lanes
NUM_RSUS = 21 # number of RSUs
RSU_SPACING = 100 # meters
RSU_ANTENNA_HEIGHT = 5 # meters
VEHICLE_ANTENNA_HEIGHT = 1.5 # meters
VEHICLE_TRANSMIT_POWER = 23 # dBm
CARRIER_FREQUENCY = 5.9e9 # Hz
SPEED_OF_LIGHT = 3e8 # m/s
NOISE_FIGURE = 0 # dB
NOISE_POWER_DENSITY = -174 + NOISE_FIGURE # dBm/Hz
BANDWIDTH = 10e6 # Hz
ANTENNA_GAIN = 3 # dBi
SHADOWING_STD_DEV = 3 # dB
CHANNEL_FEEDBACK_DELAY = 0.5e-3 # seconds
NUM_RESOURCE_BLOCKS = 20 # Number of resource blocks in the system
BW_PER_RB = BANDWIDTH / NUM_RESOURCE_BLOCKS # Bandwidth per resource block in Hz
DEFAULT_EPSILON = 1e-6
MINIMUM_RATE_SUCCESS_CHANCE_THRESHOLD = 0.75 # Minimum success chance for a rate to be considered successful
# Derived parameters
RSUpositionsX = [i * RSU_SPACING for i in range(NUM_RSUS)] # 0 100 200 ... 2000
RSUpositionY = NUM_LANES * LANE_WIDTH / 2 # All RSUs are at the same Y position

# --- Hyperparameters ---
NUM_COMMUNICATION_ROUNDS = 1000
NUM_LOCAL_STEPS = 3
LOCAL_LEARNING_RATE = 0.1
EVAL_EVERY = 5
NUM_CLASSES_PER_VEHICLE_MIN = 1 # for non-IID
NUM_CLASSES_PER_VEHICLE_MAX = 3 # for non-IID
BATCH_SIZE = 32
FED_PROX_TERM = 0.0025
LR_DECAY_ROUND=25

CURRENT_CASE=2
if CURRENT_CASE==1: # CIFAR10 -> IID
    IID_DISTRIBUTION = True
    NOF_SAMPLES_PER_CLASS_PER_VEHICLE = 500
    NUM_CLASSES_PER_VEHICLE = 10
    NUM_TOTAL_TRAINING_SAMPLES = 50000
    NUM_TOTAL_CLASSES = 10
    NOF_SAMPLES_PER_CLASS = 5000
    NOF_SAMPLES_PER_VEHICLE_MIN = 2500
    NOF_SAMPLES_PER_VEHICLE_MAX = 7500
    MODEL_SIZE = 4.38e6 #bits

elif CURRENT_CASE==2: # CIFAR10 -> NON-IID
    IID_DISTRIBUTION = False
    NOF_SAMPLES_PER_CLASS_PER_VEHICLE = 5000
    NUM_TOTAL_TRAINING_SAMPLES = 50000
    NUM_TOTAL_CLASSES = 10
    NOF_SAMPLES_PER_CLASS = 5000
    NOF_SAMPLES_PER_VEHICLE_MIN = 2500
    NOF_SAMPLES_PER_VEHICLE_MAX = 7500
    MODEL_SIZE = 4.38e6 #bits


